/**
 * Fetches initial data from the ticket that is being verified.
 * Checks whether the ticket has already been used or not. The webpage displays
 * green or red text indicating the status of the ticket depending on whether the
 * ticket is used or not. If the ticket isn't used, a button to use the ticket
 * is displayed, if the ticket is used, a button to close the webpage is displayed.
 * Displays the event that the ticket was purchased for.
 * 
 * @param {string} code is the code associated with the ticket that is being checked
 * The code must be one generated by the Go Native Ticketing API.
 * @param {int} ticket_id is the id of the ticket associated with the ticket that
 * is being checked. Must correspond to the same ticket as code.
 */
function initializePage(code, ticket_id) {
    url1 = "http://34.68.96.15/api/tickets/" + ticket_id + "/"
    fetch(url1, {
        method: "GET"
    }).then((res) => res.json()).then((data) => {
        let result = document.querySelector('.event');
        result.outerHTML = '<h1><i>' + data["event"] + '</i></h1>'
    })

    url2 = 'http://34.68.96.15/api/validation/' + code + '/'
    let result = document.querySelector('.result');
    let buttonBlock = document.querySelector('.use');
    fetch(url2)
        .then((res) => res.json()).then((data) => {
            if (data[1]) {
                result.innerHTML = '<h1 style="color:#01e806">' + data[0] + '</h1>'
            } else {
                buttonBlock.remove()
                result.innerHTML = '<h1 style="color:#ff1006">' + data[0] + '</h1>'
            }
    })

}

/**
 * Marks the ticket corresponding to the provided ticket id as used, making the
 * ticket invalid for further use. Displays a message confirmaing the use of the
 * ticket on the webpage, and a button to close the verification page.
 * 
 * @param {int} ticket_id is the id of the ticket to be marked as used.
 */
function useTicket(ticket_id) {
    url = "http://34.68.96.15/api/tickets/use/" + ticket_id + "/"
    let result = document.querySelector('.result');
    fetch(url, {
        method: "PUT"
    }).then((res) => res.json()).then((data) => {
        result.innerHTML = '<h1 style="color:#ff1006">Ticket Used</h1><br>\
            <p>This ticket is now invalid for further use.</p>'
        let buttonBlock = document.querySelector('.use');
        buttonBlock.remove()
    })
}

/**
 * Closes the current window.
 */
function closeTab()
{
    window.opener = self;
    window.close();
}
